# Generated by Django 4.2 on 2023-08-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cusorders_order_id_cusorders_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cusorders',
            name='id',
        ),
        migrations.AlterField(
            model_name='cusorders',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
