# Generated by Django 4.1.7 on 2023-07-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_item_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse tempora officiis, libero, eum nobis magnam fugiat totam voluptatibus veritatis error facilis fuga impedit quos pariatur at eligendi. Vero, veniam doloribus!', max_length=300),
        ),
    ]
